### ISSUE TITLE
Html preview

### ISSUE THREAD

**Issue by ewallace** [FlicAnderson/20201127-gitflow-workshop#8]
Hi,
I'm having trouble previewing the html file here, which is an obstacle to reusing this great material!

I mean the html slides here:
https://github.com/FlicAnderson/20201127-gitflow-workshop/blob/main/workshop_slides.html

I tried htmlpreview:
https://htmlpreview.github.io/?https://github.com/FlicAnderson/20201127-gitflow-workshop/blob/main/workshop_slides.html

This was not visible in either Safari or Chrome browsers on Mac OS. However, when I downloaded the raw html file I could open it fine on safari locally?

I wonder if this might be fixable with a couple of lines of "how to use this workshop" in the README.md - including a link to the html displaying as slides? Or by putting the slides on some kind of slideshare or zenodo thing?

**Comment by FlicAnderson** [comment]
@ewallace I haven't found any better way of viewing the html slides than just downloading the raw html from the repo and viewing locally, sorry.  

The slideshare/zenodo idea is a good one, but I'll try and PDF the material and upload the PDF to the repo - this might be a better option, especially since it's not being updated.

**Comment by FlicAnderson** [comment]
Added content on how to reuse the slides material to the README file. 

Updated the reuse this material slide in the deck.  

Removed speaker tags on outline slide in deck.  

Regenerated slides & saved PDF version from html, added PDF to repo. 

Commit 4512616a7a747e715de44b4cbe144bf7679366d0 should close issue #8 @ewallace
